version: "3"
services:
  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid-proxy
    ports:
      - "3128:3128"
    volumes:
      - squid-cache:/var/spool/squid
      - squid-logs:/var/log/squid
    dns:
      - 1.1.1.1
    networks:
      - my-network

  java-debian-dev:
    build:
      context: ./go-debian-dev
    environment:
      - HTTP_PROXY=http://squid-proxy:3128
      - HTTPS_PROXY=http://squid-proxy:3128
      - http_proxy=http://squid-proxy:3128
      - https_proxy=http://squid-proxy:3128
    dns:
      - 1.1.1.1
    volumes:
      - ${PACKAGE_DIR}:/package # Use environment variable for volume path
    env_file:
      - .env
    networks:
      - my-network
    tty: true
    stdin_open: true
    entrypoint: ["bash"]
    container_name: java-debian-dev

networks:
  my-network:
    driver: bridge

volumes:
  squid-cache:
  squid-logs:
